cmake -G "Visual Studio 9 2008" ^
	-D PEDANTIC=TRUE ^
	-D WITH_QSPATIALITE=TRUE ^
	-D WITH_MAPSERVER=TRUE ^
	-D MAPSERVER_SKIP_ECW=TRUE ^
	-D WITH_GLOBE=TRUE ^
	-D WITH_TOUCH=TRUE ^
	-D WITH_ORACLE=TRUE ^
	-D CMAKE_BUILD_TYPE=Release ^
	-D GRASS_PREFIX=%O4W_ROOT%/apps/grass/grass-6.4.3 ^
	-D CMAKE_INSTALL_PREFIX=D:/builds/ng ^
	%SRCDIR%

pause
