# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\dev\QTiles\ui\qtilesdialogbase.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(533, 681)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 515, 619))
        self.scrollAreaWidgetContents.setStyleSheet(_fromUtf8("valign:top"))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(9, 6, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.rbOutputNGM = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOutputNGM.sizePolicy().hasHeightForWidth())
        self.rbOutputNGM.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ngm_index_24x24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rbOutputNGM.setIcon(icon)
        self.rbOutputNGM.setObjectName(_fromUtf8("rbOutputNGM"))
        self.horizontalLayout_3.addWidget(self.rbOutputNGM)
        self.lInfoIconOutputNGM = QtGui.QLabel(self.groupBox)
        self.lInfoIconOutputNGM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lInfoIconOutputNGM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoIconOutputNGM.setOpenExternalLinks(False)
        self.lInfoIconOutputNGM.setObjectName(_fromUtf8("lInfoIconOutputNGM"))
        self.horizontalLayout_3.addWidget(self.lInfoIconOutputNGM)
        self.lBlank_3 = QtGui.QLabel(self.groupBox)
        self.lBlank_3.setText(_fromUtf8(""))
        self.lBlank_3.setObjectName(_fromUtf8("lBlank_3"))
        self.horizontalLayout_3.addWidget(self.lBlank_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.rbOutputZip = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOutputZip.sizePolicy().hasHeightForWidth())
        self.rbOutputZip.setSizePolicy(sizePolicy)
        self.rbOutputZip.setStyleSheet(_fromUtf8(""))
        self.rbOutputZip.setObjectName(_fromUtf8("rbOutputZip"))
        self.horizontalLayout_4.addWidget(self.rbOutputZip)
        self.lInfoIconOutputZip = QtGui.QLabel(self.groupBox)
        self.lInfoIconOutputZip.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lInfoIconOutputZip.setText(_fromUtf8("<a href=\"infoOutpuZip\"><img src=\":/icons/info.png\"/></a>"))
        self.lInfoIconOutputZip.setTextFormat(QtCore.Qt.RichText)
        self.lInfoIconOutputZip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoIconOutputZip.setOpenExternalLinks(False)
        self.lInfoIconOutputZip.setObjectName(_fromUtf8("lInfoIconOutputZip"))
        self.horizontalLayout_4.addWidget(self.lInfoIconOutputZip)
        self.lBlank_1 = QtGui.QLabel(self.groupBox)
        self.lBlank_1.setText(_fromUtf8(""))
        self.lBlank_1.setObjectName(_fromUtf8("lBlank_1"))
        self.horizontalLayout_4.addWidget(self.lBlank_1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rbOutputDir = QtGui.QRadioButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOutputDir.sizePolicy().hasHeightForWidth())
        self.rbOutputDir.setSizePolicy(sizePolicy)
        self.rbOutputDir.setObjectName(_fromUtf8("rbOutputDir"))
        self.horizontalLayout_2.addWidget(self.rbOutputDir)
        self.lInfoIconOutputDir = QtGui.QLabel(self.groupBox)
        self.lInfoIconOutputDir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lInfoIconOutputDir.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lInfoIconOutputDir.setOpenExternalLinks(False)
        self.lInfoIconOutputDir.setObjectName(_fromUtf8("lInfoIconOutputDir"))
        self.horizontalLayout_2.addWidget(self.lInfoIconOutputDir)
        self.lBlank_2 = QtGui.QLabel(self.groupBox)
        self.lBlank_2.setText(_fromUtf8(""))
        self.lBlank_2.setObjectName(_fromUtf8("lBlank_2"))
        self.horizontalLayout_2.addWidget(self.lBlank_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.leRootDir = QtGui.QLineEdit(self.groupBox)
        self.leRootDir.setObjectName(_fromUtf8("leRootDir"))
        self.gridLayout.addWidget(self.leRootDir, 4, 6, 1, 2)
        self.leZipFileName = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leZipFileName.sizePolicy().hasHeightForWidth())
        self.leZipFileName.setSizePolicy(sizePolicy)
        self.leZipFileName.setObjectName(_fromUtf8("leZipFileName"))
        self.gridLayout.addWidget(self.leZipFileName, 0, 6, 1, 1)
        self.leTilesFroNGM = QtGui.QLineEdit(self.groupBox)
        self.leTilesFroNGM.setToolTip(_fromUtf8(""))
        self.leTilesFroNGM.setPlaceholderText(_fromUtf8(""))
        self.leTilesFroNGM.setObjectName(_fromUtf8("leTilesFroNGM"))
        self.gridLayout.addWidget(self.leTilesFroNGM, 2, 6, 1, 1)
        self.leDirectoryName = QtGui.QLineEdit(self.groupBox)
        self.leDirectoryName.setObjectName(_fromUtf8("leDirectoryName"))
        self.gridLayout.addWidget(self.leDirectoryName, 1, 6, 1, 1)
        self.btnBrowse = QtGui.QPushButton(self.groupBox)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.gridLayout.addWidget(self.btnBrowse, 1, 7, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbExtentFull = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentFull.setObjectName(_fromUtf8("rbExtentFull"))
        self.gridLayout_2.addWidget(self.rbExtentFull, 1, 0, 1, 1)
        self.rbExtentCanvas = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentCanvas.setObjectName(_fromUtf8("rbExtentCanvas"))
        self.gridLayout_2.addWidget(self.rbExtentCanvas, 0, 0, 1, 1)
        self.rbExtentLayer = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentLayer.setObjectName(_fromUtf8("rbExtentLayer"))
        self.gridLayout_2.addWidget(self.rbExtentLayer, 2, 0, 1, 1)
        self.cmbLayers = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayers.sizePolicy().hasHeightForWidth())
        self.cmbLayers.setSizePolicy(sizePolicy)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout_2.addWidget(self.cmbLayers, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setContentsMargins(9, 6, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.spnZoomMin = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnZoomMin.sizePolicy().hasHeightForWidth())
        self.spnZoomMin.setSizePolicy(sizePolicy)
        self.spnZoomMin.setMaximum(40)
        self.spnZoomMin.setObjectName(_fromUtf8("spnZoomMin"))
        self.gridLayout_3.addWidget(self.spnZoomMin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet(_fromUtf8("margin-left:50"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.spnZoomMax = QtGui.QSpinBox(self.groupBox_3)
        self.spnZoomMax.setMinimum(0)
        self.spnZoomMax.setMaximum(40)
        self.spnZoomMax.setProperty("value", 18)
        self.spnZoomMax.setObjectName(_fromUtf8("spnZoomMax"))
        self.gridLayout_3.addWidget(self.spnZoomMax, 0, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.grpParameters = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.grpParameters.setProperty("collapsed", True)
        self.grpParameters.setProperty("saveCollapsedState", True)
        self.grpParameters.setObjectName(_fromUtf8("grpParameters"))
        self.gridlayout = QtGui.QGridLayout(self.grpParameters)
        self.gridlayout.setContentsMargins(-1, 6, -1, -1)
        self.gridlayout.setVerticalSpacing(3)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.chkWriteViewer = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteViewer.setObjectName(_fromUtf8("chkWriteViewer"))
        self.gridlayout.addWidget(self.chkWriteViewer, 20, 0, 1, 1)
        self.chkMBTilesCompression = QtGui.QCheckBox(self.grpParameters)
        self.chkMBTilesCompression.setObjectName(_fromUtf8("chkMBTilesCompression"))
        self.gridlayout.addWidget(self.chkMBTilesCompression, 14, 0, 1, 1)
        self.chkWriteMapurl = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteMapurl.setObjectName(_fromUtf8("chkWriteMapurl"))
        self.gridlayout.addWidget(self.chkWriteMapurl, 18, 0, 1, 1)
        self.chkWriteJson = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteJson.setObjectName(_fromUtf8("chkWriteJson"))
        self.gridlayout.addWidget(self.chkWriteJson, 16, 0, 1, 1)
        self.chkTMSConvention = QtGui.QCheckBox(self.grpParameters)
        self.chkTMSConvention.setObjectName(_fromUtf8("chkTMSConvention"))
        self.gridlayout.addWidget(self.chkTMSConvention, 11, 0, 1, 1)
        self.spnTileHeight = QtGui.QSpinBox(self.grpParameters)
        self.spnTileHeight.setEnabled(True)
        self.spnTileHeight.setMinimum(128)
        self.spnTileHeight.setMaximum(2048)
        self.spnTileHeight.setProperty("value", 256)
        self.spnTileHeight.setObjectName(_fromUtf8("spnTileHeight"))
        self.gridlayout.addWidget(self.spnTileHeight, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.grpParameters)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.chkLockRatio = QtGui.QCheckBox(self.grpParameters)
        self.chkLockRatio.setObjectName(_fromUtf8("chkLockRatio"))
        self.gridlayout.addWidget(self.chkLockRatio, 0, 2, 2, 1)
        self.spnTileWidth = QtGui.QSpinBox(self.grpParameters)
        self.spnTileWidth.setMinimum(128)
        self.spnTileWidth.setMaximum(2048)
        self.spnTileWidth.setProperty("value", 256)
        self.spnTileWidth.setObjectName(_fromUtf8("spnTileWidth"))
        self.gridlayout.addWidget(self.spnTileWidth, 0, 1, 1, 1)
        self.lblHeight = QtGui.QLabel(self.grpParameters)
        self.lblHeight.setEnabled(True)
        self.lblHeight.setObjectName(_fromUtf8("lblHeight"))
        self.gridlayout.addWidget(self.lblHeight, 1, 0, 1, 1)
        self.chkAntialiasing = QtGui.QCheckBox(self.grpParameters)
        self.chkAntialiasing.setObjectName(_fromUtf8("chkAntialiasing"))
        self.gridlayout.addWidget(self.chkAntialiasing, 8, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.grpParameters)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.grpParameters)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.grpParameters)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.spnTransparency = QtGui.QSpinBox(self.grpParameters)
        self.spnTransparency.setMaximum(255)
        self.spnTransparency.setProperty("value", 255)
        self.spnTransparency.setObjectName(_fromUtf8("spnTransparency"))
        self.gridlayout.addWidget(self.spnTransparency, 4, 1, 1, 1)
        self.spnQuality = QtGui.QSpinBox(self.grpParameters)
        self.spnQuality.setMinimum(0)
        self.spnQuality.setMaximum(100)
        self.spnQuality.setProperty("value", 0)
        self.spnQuality.setObjectName(_fromUtf8("spnQuality"))
        self.gridlayout.addWidget(self.spnQuality, 5, 1, 1, 1)
        self.cmbFormat = QtGui.QComboBox(self.grpParameters)
        self.cmbFormat.setObjectName(_fromUtf8("cmbFormat"))
        self.cmbFormat.addItem(_fromUtf8(""))
        self.cmbFormat.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbFormat, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.grpParameters)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout.addWidget(self.label_8, 5, 2, 1, 1)
        self.chkRenderOutsideTiles = QtGui.QCheckBox(self.grpParameters)
        self.chkRenderOutsideTiles.setEnabled(True)
        self.chkRenderOutsideTiles.setChecked(True)
        self.chkRenderOutsideTiles.setObjectName(_fromUtf8("chkRenderOutsideTiles"))
        self.gridlayout.addWidget(self.chkRenderOutsideTiles, 12, 0, 1, 1)
        self.chkWriteOverview = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteOverview.setObjectName(_fromUtf8("chkWriteOverview"))
        self.gridlayout.addWidget(self.chkWriteOverview, 17, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grpParameters)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "QTiles", None))
        self.groupBox.setTitle(_translate("Dialog", "Output", None))
        self.rbOutputNGM.setText(_translate("Dialog", "NGM", None))
        self.lInfoIconOutputNGM.setText(_translate("Dialog", "<a href=\"infoOutpuZip\"><img src=\":/icons/info.png\"/></a>", None))
        self.rbOutputZip.setText(_translate("Dialog", "File", None))
        self.rbOutputDir.setText(_translate("Dialog", "Directory", None))
        self.lInfoIconOutputDir.setText(_translate("Dialog", "<a href=\"infoOutpuZip\"><img src=\":/icons/info.png\"/></a>", None))
        self.label_4.setText(_translate("Dialog", "Tileset name", None))
        self.btnBrowse.setText(_translate("Dialog", "Browse...", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Extent", None))
        self.rbExtentFull.setText(_translate("Dialog", "Full extent", None))
        self.rbExtentCanvas.setText(_translate("Dialog", "Canvas extent", None))
        self.rbExtentLayer.setText(_translate("Dialog", "Layer extent", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Zoom", None))
        self.label_2.setText(_translate("Dialog", "Maximum zoom", None))
        self.label.setText(_translate("Dialog", "Minimum zoom", None))
        self.grpParameters.setTitle(_translate("Dialog", "Parameters", None))
        self.chkWriteViewer.setText(_translate("Dialog", "Write Leaflet-based viewer", None))
        self.chkMBTilesCompression.setText(_translate("Dialog", "Use MBTiles compression", None))
        self.chkWriteMapurl.setText(_translate("Dialog", "Write .mapurl file", None))
        self.chkWriteJson.setText(_translate("Dialog", "Write .json metadata", None))
        self.chkTMSConvention.setText(_translate("Dialog", "Use TMS tiles convention (Slippy Map by default)", None))
        self.label_3.setText(_translate("Dialog", "Tile width", None))
        self.chkLockRatio.setText(_translate("Dialog", "Lock 1:1 ratio", None))
        self.lblHeight.setText(_translate("Dialog", "Tile height", None))
        self.chkAntialiasing.setText(_translate("Dialog", "Make lines appear less jagged at the expence of some drawing performance", None))
        self.label_5.setText(_translate("Dialog", "Background transparency", None))
        self.label_6.setText(_translate("Dialog", "Format", None))
        self.label_7.setText(_translate("Dialog", "Quality", None))
        self.cmbFormat.setItemText(0, _translate("Dialog", "PNG", None))
        self.cmbFormat.setItemText(1, _translate("Dialog", "JPG", None))
        self.label_8.setText(_translate("Dialog", "(0-100)", None))
        self.chkRenderOutsideTiles.setText(_translate("Dialog", "Render tiles outside of layers extents (within combined extent)", None))
        self.chkWriteOverview.setText(_translate("Dialog", "Write overview image file", None))

from qgis.gui import QgsCollapsibleGroupBox
