# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qtilesdialogbase.ui'
#
# Created: Wed Jan 14 17:24:42 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(526, 441)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -197, 510, 600))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rbOutputZip = QtGui.QRadioButton(self.groupBox)
        self.rbOutputZip.setObjectName(_fromUtf8("rbOutputZip"))
        self.gridLayout.addWidget(self.rbOutputZip, 0, 0, 1, 1)
        self.leZipFileName = QtGui.QLineEdit(self.groupBox)
        self.leZipFileName.setObjectName(_fromUtf8("leZipFileName"))
        self.gridLayout.addWidget(self.leZipFileName, 0, 1, 1, 1)
        self.btnBrowse = QtGui.QPushButton(self.groupBox)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.gridLayout.addWidget(self.btnBrowse, 0, 2, 2, 1)
        self.rbOutputDir = QtGui.QRadioButton(self.groupBox)
        self.rbOutputDir.setObjectName(_fromUtf8("rbOutputDir"))
        self.gridLayout.addWidget(self.rbOutputDir, 1, 0, 1, 1)
        self.leDirectoryName = QtGui.QLineEdit(self.groupBox)
        self.leDirectoryName.setObjectName(_fromUtf8("leDirectoryName"))
        self.gridLayout.addWidget(self.leDirectoryName, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.leRootDir = QtGui.QLineEdit(self.groupBox)
        self.leRootDir.setObjectName(_fromUtf8("leRootDir"))
        self.gridLayout.addWidget(self.leRootDir, 2, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbExtentCanvas = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentCanvas.setObjectName(_fromUtf8("rbExtentCanvas"))
        self.gridLayout_2.addWidget(self.rbExtentCanvas, 0, 0, 1, 1)
        self.rbExtentFull = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentFull.setObjectName(_fromUtf8("rbExtentFull"))
        self.gridLayout_2.addWidget(self.rbExtentFull, 1, 0, 1, 1)
        self.rbExtentLayer = QtGui.QRadioButton(self.groupBox_2)
        self.rbExtentLayer.setObjectName(_fromUtf8("rbExtentLayer"))
        self.gridLayout_2.addWidget(self.rbExtentLayer, 2, 0, 1, 1)
        self.cmbLayers = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayers.sizePolicy().hasHeightForWidth())
        self.cmbLayers.setSizePolicy(sizePolicy)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout_2.addWidget(self.cmbLayers, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.spnZoomMin = QtGui.QSpinBox(self.groupBox_3)
        self.spnZoomMin.setMaximum(40)
        self.spnZoomMin.setObjectName(_fromUtf8("spnZoomMin"))
        self.gridLayout_3.addWidget(self.spnZoomMin, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.spnZoomMax = QtGui.QSpinBox(self.groupBox_3)
        self.spnZoomMax.setMinimum(0)
        self.spnZoomMax.setMaximum(40)
        self.spnZoomMax.setProperty("value", 18)
        self.spnZoomMax.setObjectName(_fromUtf8("spnZoomMax"))
        self.gridLayout_3.addWidget(self.spnZoomMax, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.grpParameters = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.grpParameters.setProperty("collapsed", True)
        self.grpParameters.setProperty("saveCollapsedState", True)
        self.grpParameters.setObjectName(_fromUtf8("grpParameters"))
        self.gridlayout = QtGui.QGridLayout(self.grpParameters)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_3 = QtGui.QLabel(self.grpParameters)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.chkLockRatio = QtGui.QCheckBox(self.grpParameters)
        self.chkLockRatio.setObjectName(_fromUtf8("chkLockRatio"))
        self.gridlayout.addWidget(self.chkLockRatio, 0, 2, 2, 1)
        self.lblHeight = QtGui.QLabel(self.grpParameters)
        self.lblHeight.setEnabled(True)
        self.lblHeight.setObjectName(_fromUtf8("lblHeight"))
        self.gridlayout.addWidget(self.lblHeight, 1, 0, 1, 1)
        self.spnTileWidth = QtGui.QSpinBox(self.grpParameters)
        self.spnTileWidth.setMinimum(128)
        self.spnTileWidth.setMaximum(2048)
        self.spnTileWidth.setProperty("value", 256)
        self.spnTileWidth.setObjectName(_fromUtf8("spnTileWidth"))
        self.gridlayout.addWidget(self.spnTileWidth, 0, 1, 1, 1)
        self.spnTileHeight = QtGui.QSpinBox(self.grpParameters)
        self.spnTileHeight.setEnabled(True)
        self.spnTileHeight.setMinimum(128)
        self.spnTileHeight.setMaximum(2048)
        self.spnTileHeight.setProperty("value", 256)
        self.spnTileHeight.setObjectName(_fromUtf8("spnTileHeight"))
        self.gridlayout.addWidget(self.spnTileHeight, 1, 1, 1, 1)
        self.chkAntialiasing = QtGui.QCheckBox(self.grpParameters)
        self.chkAntialiasing.setObjectName(_fromUtf8("chkAntialiasing"))
        self.gridlayout.addWidget(self.chkAntialiasing, 6, 0, 1, 3)
        self.chkTMSConvention = QtGui.QCheckBox(self.grpParameters)
        self.chkTMSConvention.setObjectName(_fromUtf8("chkTMSConvention"))
        self.gridlayout.addWidget(self.chkTMSConvention, 7, 0, 1, 3)
        self.chkWriteMapurl = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteMapurl.setObjectName(_fromUtf8("chkWriteMapurl"))
        self.gridlayout.addWidget(self.chkWriteMapurl, 8, 0, 1, 3)
        self.chkWriteViewer = QtGui.QCheckBox(self.grpParameters)
        self.chkWriteViewer.setObjectName(_fromUtf8("chkWriteViewer"))
        self.gridlayout.addWidget(self.chkWriteViewer, 9, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.grpParameters)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.cmbFormat = QtGui.QComboBox(self.grpParameters)
        self.cmbFormat.setObjectName(_fromUtf8("cmbFormat"))
        self.cmbFormat.addItem(_fromUtf8(""))
        self.cmbFormat.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cmbFormat, 3, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.grpParameters)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spnTransparency = QtGui.QSpinBox(self.grpParameters)
        self.spnTransparency.setMaximum(255)
        self.spnTransparency.setProperty("value", 255)
        self.spnTransparency.setObjectName(_fromUtf8("spnTransparency"))
        self.gridlayout.addWidget(self.spnTransparency, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.grpParameters)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.spnQuality = QtGui.QSpinBox(self.grpParameters)
        self.spnQuality.setMinimum(0)
        self.spnQuality.setMaximum(100)
        self.spnQuality.setProperty("value", 0)
        self.spnQuality.setObjectName(_fromUtf8("spnQuality"))
        self.gridlayout.addWidget(self.spnQuality, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.grpParameters)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout.addWidget(self.label_8, 5, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.grpParameters)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "QTiles", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOutputZip.setText(QtGui.QApplication.translate("Dialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.rbOutputDir.setText(QtGui.QApplication.translate("Dialog", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Tileset name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.rbExtentCanvas.setText(QtGui.QApplication.translate("Dialog", "Canvas extent", None, QtGui.QApplication.UnicodeUTF8))
        self.rbExtentFull.setText(QtGui.QApplication.translate("Dialog", "Full extent", None, QtGui.QApplication.UnicodeUTF8))
        self.rbExtentLayer.setText(QtGui.QApplication.translate("Dialog", "Layer extent", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Minimum zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Maximum zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.grpParameters.setTitle(QtGui.QApplication.translate("Dialog", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Tile width", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLockRatio.setText(QtGui.QApplication.translate("Dialog", "Lock 1:1 ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHeight.setText(QtGui.QApplication.translate("Dialog", "Tile height", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAntialiasing.setText(QtGui.QApplication.translate("Dialog", "Make lines appear less jagged at the expence of some drawing performance", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTMSConvention.setText(QtGui.QApplication.translate("Dialog", "Use TMS tiles convention (Slippy Map by default)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWriteMapurl.setText(QtGui.QApplication.translate("Dialog", "Write .mapurl file", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWriteViewer.setText(QtGui.QApplication.translate("Dialog", "Write Leaflet-based viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFormat.setItemText(0, QtGui.QApplication.translate("Dialog", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFormat.setItemText(1, QtGui.QApplication.translate("Dialog", "JPG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Background transparency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "(0-100)", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsCollapsibleGroupBox
